language: java

addons:
  hosts:
    - short-hostname
  hostname: short-hostname

matrix:
  include:
    - jdk: openjdk7
      dist: precise
    - jdk: oraclejdk7
      dist: precise
    - jdk: oraclejdk8
    - jdk: oraclejdk9

notifications:
  email:
    on_success: never

sudo: false

script:
  - ./gradlew clean test
  - if [[ ${TRAVIS_JDK_VERSION} == "oraclejdk8" ]]; then ./gradlew coberturaReport coveralls; fi

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
